### ISSUE TITLE
Formalize testcase

### ISSUE THREAD

**Issue by stasinos** [data-eng/navgreen#9]
Make a formal testcase out of the testing code (cf. Issue #6) and start using a build tool that automatically tests the codebase.

**Comment by stasinos** [comment]
I will test poetry as a build tool, never used it before but seems worth a try.

**Comment by stasinos** [comment]
@tatiana-boura see branch `issue-9-buildtool` and comment on whether this setup is compatible with your dev environment

**Comment by tatiana-boura** [comment]
The setup is compatible.

However, ```poetry install``` fails if I include the _hist_data_analysis_ package in ```pyproject.toml```. Its inclusion  triggers the following (expected) error:

**Error**: [...] /navgreen/hist_data_analysis doesn't contain any elements.

**Comment by stasinos** [comment]
I am thinking of using (unittest)[https://docs.python.org/3/library/unittest.html] as a testing framework. Any objections or alternative suggestions?

**Comment by tatiana-boura** [comment]
No issues here. It appears to be widely used and follows the expected format of a unit testing module. It also reminds me of [acutest](https://github.com/mity/acutest), which I've previously used (for C programs).

I'm sure you've encountered the pytest vs unittest [debate](https://builtin.com/data-science/pytest-vs-unittest), but considering the nature of our project, which doesn't require external dependencies, I believe unittest is the best choice.

However, since I haven't personally worked with these and don't have hands-on experience with their advantages and disadvantages, I recommend we use unittest, but also remain open to considering pytest as an option if things do not go as planned.
